set top [ipx::current_core];
::set_property vendor {user.org} $top;
::set_property library {user} $top;
::set_property version {1.0} $top;
::set_property vlnv {user.org:user:ExampleRocketSystem:1.0} $top;
::set_property core_revision {1} $top;
::set_property description {ExampleRocketSystem_v1_0} $top;
::set_property display_name {ExampleRocketSystem_v1_0} $top;
::set_property xilinx_version {2018.3} $top;
::set_property tags {ui.data.coregen.dd@55b2e241_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@7ca38cf2_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@746921b3_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@537812c0_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@1406103e_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@4c147e98_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@28e182a3_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@48f66129_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@437ab955_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@2a5c56fc_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@52622646_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@6cc71b5a_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@28f432d2_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@2386e5e4_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@5084cfd4_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@3658094c_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@4e7db665_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports ui.data.coregen.dd@3cad8c31_ARCHIVE_LOCATION rocket_ip_core/rocket_ip_core.srcs/sources_1/imports} $top;
::set_property supports_vivado {true} $top;
::set_property definition_source {package_project} $top;
::set_property hide_in_gui {false} $top;
::set_property taxonomy {/UserIP} $top;
::set_property supported_families {virtex7 Production qvirtex7 Production kintex7 Production kintex7l Production qkintex7 Production qkintex7l Production artix7 Production artix7l Production aartix7 Production qartix7 Production zynq Production qzynq Production azynq Production spartan7 Production aspartan7 Production virtexu Production zynquplus Production virtexuplus Production virtexuplusHBM Production virtexuplus58g Production kintexuplus Production kintexu Production} $top;
# Add port objects
set current_port [::ipx::add_port clock $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port reset $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port interrupts $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_ready $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_valid $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_id $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_addr $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {31} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_len $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {7} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_size $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_burst $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_lock $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_cache $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_prot $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_aw_bits_qos $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_w_ready $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_w_valid $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_w_bits_data $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {63} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_w_bits_strb $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {7} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_w_bits_last $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_b_ready $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_b_valid $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_b_bits_id $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_b_bits_resp $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_ready $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_valid $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_id $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_addr $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {31} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_len $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {7} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_size $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_burst $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_lock $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_cache $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_prot $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_ar_bits_qos $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_r_ready $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_r_valid $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mem_axi4_0_r_bits_id $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_r_bits_data $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {63} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_r_bits_resp $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mem_axi4_0_r_bits_last $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_ready $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_valid $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_id $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_addr $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {30} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_len $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {7} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_size $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_burst $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_lock $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_cache $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_prot $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_aw_bits_qos $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_w_ready $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_w_valid $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_w_bits_data $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {63} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_w_bits_strb $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {7} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_w_bits_last $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_b_ready $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_b_valid $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_b_bits_id $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_b_bits_resp $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_ready $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_valid $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_id $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_addr $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {30} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_len $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {7} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_size $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_burst $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_lock $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_cache $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_prot $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {2} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_ar_bits_qos $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {3} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_r_ready $top];
::set_property direction {out} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_r_valid $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_r_bits_id $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {5} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_r_bits_data $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {63} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_r_bits_resp $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property size_left {1} $current_port;
::set_property type_name {std_logic_vector} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
set current_port [::ipx::add_port mmio_axi4_0_r_bits_last $top];
::set_property direction {in} $current_port;
::set_property latency {0} $current_port;
::set_property type_name {std_logic} $current_port;
::set_property view_name_refs {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} $current_port;
::set_property is_vector {false} $current_port;
# Add user_parameter objects
set current_user_parameter [::ipx::add_user_parameter Component_Name $top];
::set_property ipxact_id {PARAM_VALUE.Component_Name} $current_user_parameter;
::set_property usage {all} $current_user_parameter;
::set_property order {1.000000} $current_user_parameter;
::set_property value {ExampleRocketSystem_v1_0} $current_user_parameter;
::set_property value_resolve_type {user} $current_user_parameter;
::set_property value_source {default} $current_user_parameter;
::set_property value_validation_type {none} $current_user_parameter;
# Add address_space objects
set current_address_space [::ipx::add_address_space mem_if $top];
::set_property range {4294967296} $current_address_space;
::set_property width {64} $current_address_space;
set current_address_space [::ipx::add_address_space mmio_if $top];
::set_property range {4294967296} $current_address_space;
::set_property width {64} $current_address_space;
# Add bus_interface objects
set current_bus_interface [::ipx::add_bus_interface reset $top];
::set_property bus_type_vendor {xilinx.com} $current_bus_interface;
::set_property bus_type_library {signal} $current_bus_interface;
::set_property bus_type_name {reset} $current_bus_interface;
::set_property bus_type_version {1.0} $current_bus_interface;
::set_property bus_type_vlnv {xilinx.com:signal:reset:1.0} $current_bus_interface;
::set_property abstraction_type_vendor {xilinx.com} $current_bus_interface;
::set_property abstraction_type_library {signal} $current_bus_interface;
::set_property abstraction_type_name {reset_rtl} $current_bus_interface;
::set_property abstraction_type_version {1.0} $current_bus_interface;
::set_property abstraction_type_vlnv {xilinx.com:signal:reset_rtl:1.0} $current_bus_interface;
::set_property master_base_address {0} $current_bus_interface;
::set_property monitor_interface_mode {master} $current_bus_interface;
# Add bus_parameter objects
set current_bus_parameter [::ipx::add_bus_parameter POLARITY $current_bus_interface];
::set_property ipxact_id {BUSIFPARAM_VALUE.RESET.POLARITY} $current_bus_parameter;
::set_property usage {all} $current_bus_parameter;
::set_property order {0.000000} $current_bus_parameter;
::set_property value {ACTIVE_HIGH} $current_bus_parameter;
::set_property value_source {default} $current_bus_parameter;
::set_property value_validation_type {none} $current_bus_parameter;
# Add port_map objects
set current_port_map [::ipx::add_port_map RST $current_bus_interface];
::set_property logical_name {RST} $current_port_map;
::set_property physical_name {reset} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_bus_interface [::ipx::add_bus_interface clock $top];
::set_property bus_type_vendor {xilinx.com} $current_bus_interface;
::set_property bus_type_library {signal} $current_bus_interface;
::set_property bus_type_name {clock} $current_bus_interface;
::set_property bus_type_version {1.0} $current_bus_interface;
::set_property bus_type_vlnv {xilinx.com:signal:clock:1.0} $current_bus_interface;
::set_property abstraction_type_vendor {xilinx.com} $current_bus_interface;
::set_property abstraction_type_library {signal} $current_bus_interface;
::set_property abstraction_type_name {clock_rtl} $current_bus_interface;
::set_property abstraction_type_version {1.0} $current_bus_interface;
::set_property abstraction_type_vlnv {xilinx.com:signal:clock_rtl:1.0} $current_bus_interface;
::set_property master_base_address {0} $current_bus_interface;
::set_property monitor_interface_mode {master} $current_bus_interface;
# Add bus_parameter objects
set current_bus_parameter [::ipx::add_bus_parameter ASSOCIATED_RESET $current_bus_interface];
::set_property ipxact_id {BUSIFPARAM_VALUE.CLOCK.ASSOCIATED_RESET} $current_bus_parameter;
::set_property usage {all} $current_bus_parameter;
::set_property order {0.000000} $current_bus_parameter;
::set_property value {reset} $current_bus_parameter;
::set_property value_source {default} $current_bus_parameter;
::set_property value_validation_type {none} $current_bus_parameter;
set current_bus_parameter [::ipx::add_bus_parameter ASSOCIATED_BUSIF $current_bus_interface];
::set_property description {List of bus interface names separated by colons. For example, m_axis_a:s_axis_b:s_axis_c} $current_bus_parameter;
::set_property ipxact_id {BUSIFPARAM_VALUE.CLOCK.ASSOCIATED_BUSIF} $current_bus_parameter;
::set_property usage {all} $current_bus_parameter;
::set_property order {0.000000} $current_bus_parameter;
::set_property value {mem_if:mmio_if} $current_bus_parameter;
::set_property value_source {default} $current_bus_parameter;
::set_property value_validation_type {none} $current_bus_parameter;
# Add port_map objects
set current_port_map [::ipx::add_port_map CLK $current_bus_interface];
::set_property logical_name {CLK} $current_port_map;
::set_property physical_name {clock} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_bus_interface [::ipx::add_bus_interface mem_if $top];
::set_property bus_type_vendor {xilinx.com} $current_bus_interface;
::set_property bus_type_library {interface} $current_bus_interface;
::set_property bus_type_name {aximm} $current_bus_interface;
::set_property bus_type_version {1.0} $current_bus_interface;
::set_property bus_type_vlnv {xilinx.com:interface:aximm:1.0} $current_bus_interface;
::set_property abstraction_type_vendor {xilinx.com} $current_bus_interface;
::set_property abstraction_type_library {interface} $current_bus_interface;
::set_property abstraction_type_name {aximm_rtl} $current_bus_interface;
::set_property abstraction_type_version {1.0} $current_bus_interface;
::set_property abstraction_type_vlnv {xilinx.com:interface:aximm_rtl:1.0} $current_bus_interface;
::set_property interface_mode {master} $current_bus_interface;
::set_property master_address_space_ref {mem_if} $current_bus_interface;
::set_property master_base_address {0} $current_bus_interface;
::set_property monitor_interface_mode {master} $current_bus_interface;
# Add bus_parameter objects
set current_bus_parameter [::ipx::add_bus_parameter NUM_READ_OUTSTANDING $current_bus_interface];
::set_property ipxact_id {BUSIFPARAM_VALUE.MEM_IF.NUM_READ_OUTSTANDING} $current_bus_parameter;
::set_property usage {all} $current_bus_parameter;
::set_property order {0.000000} $current_bus_parameter;
::set_property value_source {default} $current_bus_parameter;
::set_property value_validation_type {none} $current_bus_parameter;
set current_bus_parameter [::ipx::add_bus_parameter NUM_WRITE_OUTSTANDING $current_bus_interface];
::set_property ipxact_id {BUSIFPARAM_VALUE.MEM_IF.NUM_WRITE_OUTSTANDING} $current_bus_parameter;
::set_property usage {all} $current_bus_parameter;
::set_property order {0.000000} $current_bus_parameter;
::set_property value_source {default} $current_bus_parameter;
::set_property value_validation_type {none} $current_bus_parameter;
# Add port_map objects
set current_port_map [::ipx::add_port_map WLAST $current_bus_interface];
::set_property logical_name {WLAST} $current_port_map;
::set_property physical_name {mem_axi4_0_w_bits_last} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BREADY $current_bus_interface];
::set_property logical_name {BREADY} $current_port_map;
::set_property physical_name {mem_axi4_0_b_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWLEN $current_bus_interface];
::set_property logical_name {AWLEN} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_len} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWQOS $current_bus_interface];
::set_property logical_name {AWQOS} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_qos} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWREADY $current_bus_interface];
::set_property logical_name {AWREADY} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARBURST $current_bus_interface];
::set_property logical_name {ARBURST} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_burst} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWPROT $current_bus_interface];
::set_property logical_name {AWPROT} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_prot} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RRESP $current_bus_interface];
::set_property logical_name {RRESP} $current_port_map;
::set_property physical_name {mem_axi4_0_r_bits_resp} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARPROT $current_bus_interface];
::set_property logical_name {ARPROT} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_prot} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RVALID $current_bus_interface];
::set_property logical_name {RVALID} $current_port_map;
::set_property physical_name {mem_axi4_0_r_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARLOCK $current_bus_interface];
::set_property logical_name {ARLOCK} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_lock} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWID $current_bus_interface];
::set_property logical_name {AWID} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RLAST $current_bus_interface];
::set_property logical_name {RLAST} $current_port_map;
::set_property physical_name {mem_axi4_0_r_bits_last} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARID $current_bus_interface];
::set_property logical_name {ARID} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWCACHE $current_bus_interface];
::set_property logical_name {AWCACHE} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_cache} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WREADY $current_bus_interface];
::set_property logical_name {WREADY} $current_port_map;
::set_property physical_name {mem_axi4_0_w_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WSTRB $current_bus_interface];
::set_property logical_name {WSTRB} $current_port_map;
::set_property physical_name {mem_axi4_0_w_bits_strb} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BRESP $current_bus_interface];
::set_property logical_name {BRESP} $current_port_map;
::set_property physical_name {mem_axi4_0_b_bits_resp} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BID $current_bus_interface];
::set_property logical_name {BID} $current_port_map;
::set_property physical_name {mem_axi4_0_b_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARLEN $current_bus_interface];
::set_property logical_name {ARLEN} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_len} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARQOS $current_bus_interface];
::set_property logical_name {ARQOS} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_qos} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RDATA $current_bus_interface];
::set_property logical_name {RDATA} $current_port_map;
::set_property physical_name {mem_axi4_0_r_bits_data} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BVALID $current_bus_interface];
::set_property logical_name {BVALID} $current_port_map;
::set_property physical_name {mem_axi4_0_b_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARCACHE $current_bus_interface];
::set_property logical_name {ARCACHE} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_cache} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RREADY $current_bus_interface];
::set_property logical_name {RREADY} $current_port_map;
::set_property physical_name {mem_axi4_0_r_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWVALID $current_bus_interface];
::set_property logical_name {AWVALID} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARSIZE $current_bus_interface];
::set_property logical_name {ARSIZE} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_size} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WDATA $current_bus_interface];
::set_property logical_name {WDATA} $current_port_map;
::set_property physical_name {mem_axi4_0_w_bits_data} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWSIZE $current_bus_interface];
::set_property logical_name {AWSIZE} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_size} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RID $current_bus_interface];
::set_property logical_name {RID} $current_port_map;
::set_property physical_name {mem_axi4_0_r_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARADDR $current_bus_interface];
::set_property logical_name {ARADDR} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_bits_addr} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWADDR $current_bus_interface];
::set_property logical_name {AWADDR} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_addr} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARREADY $current_bus_interface];
::set_property logical_name {ARREADY} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WVALID $current_bus_interface];
::set_property logical_name {WVALID} $current_port_map;
::set_property physical_name {mem_axi4_0_w_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARVALID $current_bus_interface];
::set_property logical_name {ARVALID} $current_port_map;
::set_property physical_name {mem_axi4_0_ar_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWLOCK $current_bus_interface];
::set_property logical_name {AWLOCK} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_lock} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWBURST $current_bus_interface];
::set_property logical_name {AWBURST} $current_port_map;
::set_property physical_name {mem_axi4_0_aw_bits_burst} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_bus_interface [::ipx::add_bus_interface mmio_if $top];
::set_property bus_type_vendor {xilinx.com} $current_bus_interface;
::set_property bus_type_library {interface} $current_bus_interface;
::set_property bus_type_name {aximm} $current_bus_interface;
::set_property bus_type_version {1.0} $current_bus_interface;
::set_property bus_type_vlnv {xilinx.com:interface:aximm:1.0} $current_bus_interface;
::set_property abstraction_type_vendor {xilinx.com} $current_bus_interface;
::set_property abstraction_type_library {interface} $current_bus_interface;
::set_property abstraction_type_name {aximm_rtl} $current_bus_interface;
::set_property abstraction_type_version {1.0} $current_bus_interface;
::set_property abstraction_type_vlnv {xilinx.com:interface:aximm_rtl:1.0} $current_bus_interface;
::set_property interface_mode {master} $current_bus_interface;
::set_property master_address_space_ref {mmio_if} $current_bus_interface;
::set_property master_base_address {0} $current_bus_interface;
::set_property monitor_interface_mode {master} $current_bus_interface;
# Add bus_parameter objects
set current_bus_parameter [::ipx::add_bus_parameter NUM_READ_OUTSTANDING $current_bus_interface];
::set_property ipxact_id {BUSIFPARAM_VALUE.MMIO_IF.NUM_READ_OUTSTANDING} $current_bus_parameter;
::set_property usage {all} $current_bus_parameter;
::set_property order {0.000000} $current_bus_parameter;
::set_property value_source {default} $current_bus_parameter;
::set_property value_validation_type {none} $current_bus_parameter;
set current_bus_parameter [::ipx::add_bus_parameter NUM_WRITE_OUTSTANDING $current_bus_interface];
::set_property ipxact_id {BUSIFPARAM_VALUE.MMIO_IF.NUM_WRITE_OUTSTANDING} $current_bus_parameter;
::set_property usage {all} $current_bus_parameter;
::set_property order {0.000000} $current_bus_parameter;
::set_property value_source {default} $current_bus_parameter;
::set_property value_validation_type {none} $current_bus_parameter;
# Add port_map objects
set current_port_map [::ipx::add_port_map WLAST $current_bus_interface];
::set_property logical_name {WLAST} $current_port_map;
::set_property physical_name {mmio_axi4_0_w_bits_last} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BREADY $current_bus_interface];
::set_property logical_name {BREADY} $current_port_map;
::set_property physical_name {mmio_axi4_0_b_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWLEN $current_bus_interface];
::set_property logical_name {AWLEN} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_len} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWQOS $current_bus_interface];
::set_property logical_name {AWQOS} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_qos} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWREADY $current_bus_interface];
::set_property logical_name {AWREADY} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARBURST $current_bus_interface];
::set_property logical_name {ARBURST} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_burst} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWPROT $current_bus_interface];
::set_property logical_name {AWPROT} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_prot} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RRESP $current_bus_interface];
::set_property logical_name {RRESP} $current_port_map;
::set_property physical_name {mmio_axi4_0_r_bits_resp} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARPROT $current_bus_interface];
::set_property logical_name {ARPROT} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_prot} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RVALID $current_bus_interface];
::set_property logical_name {RVALID} $current_port_map;
::set_property physical_name {mmio_axi4_0_r_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARLOCK $current_bus_interface];
::set_property logical_name {ARLOCK} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_lock} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWID $current_bus_interface];
::set_property logical_name {AWID} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RLAST $current_bus_interface];
::set_property logical_name {RLAST} $current_port_map;
::set_property physical_name {mmio_axi4_0_r_bits_last} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARID $current_bus_interface];
::set_property logical_name {ARID} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWCACHE $current_bus_interface];
::set_property logical_name {AWCACHE} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_cache} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WREADY $current_bus_interface];
::set_property logical_name {WREADY} $current_port_map;
::set_property physical_name {mmio_axi4_0_w_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WSTRB $current_bus_interface];
::set_property logical_name {WSTRB} $current_port_map;
::set_property physical_name {mmio_axi4_0_w_bits_strb} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BRESP $current_bus_interface];
::set_property logical_name {BRESP} $current_port_map;
::set_property physical_name {mmio_axi4_0_b_bits_resp} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BID $current_bus_interface];
::set_property logical_name {BID} $current_port_map;
::set_property physical_name {mmio_axi4_0_b_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARLEN $current_bus_interface];
::set_property logical_name {ARLEN} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_len} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARQOS $current_bus_interface];
::set_property logical_name {ARQOS} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_qos} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RDATA $current_bus_interface];
::set_property logical_name {RDATA} $current_port_map;
::set_property physical_name {mmio_axi4_0_r_bits_data} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map BVALID $current_bus_interface];
::set_property logical_name {BVALID} $current_port_map;
::set_property physical_name {mmio_axi4_0_b_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARCACHE $current_bus_interface];
::set_property logical_name {ARCACHE} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_cache} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RREADY $current_bus_interface];
::set_property logical_name {RREADY} $current_port_map;
::set_property physical_name {mmio_axi4_0_r_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWVALID $current_bus_interface];
::set_property logical_name {AWVALID} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARSIZE $current_bus_interface];
::set_property logical_name {ARSIZE} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_size} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WDATA $current_bus_interface];
::set_property logical_name {WDATA} $current_port_map;
::set_property physical_name {mmio_axi4_0_w_bits_data} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWSIZE $current_bus_interface];
::set_property logical_name {AWSIZE} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_size} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map RID $current_bus_interface];
::set_property logical_name {RID} $current_port_map;
::set_property physical_name {mmio_axi4_0_r_bits_id} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARADDR $current_bus_interface];
::set_property logical_name {ARADDR} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_bits_addr} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWADDR $current_bus_interface];
::set_property logical_name {AWADDR} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_addr} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARREADY $current_bus_interface];
::set_property logical_name {ARREADY} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_ready} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map WVALID $current_bus_interface];
::set_property logical_name {WVALID} $current_port_map;
::set_property physical_name {mmio_axi4_0_w_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map ARVALID $current_bus_interface];
::set_property logical_name {ARVALID} $current_port_map;
::set_property physical_name {mmio_axi4_0_ar_valid} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWLOCK $current_bus_interface];
::set_property logical_name {AWLOCK} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_lock} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
set current_port_map [::ipx::add_port_map AWBURST $current_bus_interface];
::set_property logical_name {AWBURST} $current_port_map;
::set_property physical_name {mmio_axi4_0_aw_bits_burst} $current_port_map;
::set_property is_logical_vector {false} $current_port_map;
::set_property is_physical_vector {false} $current_port_map;
# Add file_group objects
set current_file_group [::ipx::add_file_group xilinx_anylanguagesynthesis $top];
::set_property display_name {Synthesis} $current_file_group;
::set_property language {Verilog} $current_file_group;
::set_property model_name {ExampleRocketSystem} $current_file_group;
::set_property env_ids {:vivado.xilinx.com:synthesis} $current_file_group;
# Add file objects
set current_file [::ipx::add_file freechips.rocketchip.system.ZedboardConfig.behav_srams.v $current_file_group];
::set_property type {verilogSource} $current_file;
::set_property processing_order {normal} $current_file;
set current_file [::ipx::add_file plusarg_reader.v $current_file_group];
::set_property type {verilogSource} $current_file;
::set_property processing_order {normal} $current_file;
set current_file [::ipx::add_file freechips.rocketchip.system.ZedboardConfig.v $current_file_group];
::set_property type {verilogSource} $current_file;
::set_property processing_order {normal} $current_file;
set current_file_group [::ipx::add_file_group xilinx_anylanguagebehavioralsimulation $top];
::set_property display_name {Simulation} $current_file_group;
::set_property language {Verilog} $current_file_group;
::set_property model_name {ExampleRocketSystem} $current_file_group;
::set_property env_ids {:vivado.xilinx.com:simulation} $current_file_group;
# Add file objects
set current_file [::ipx::add_file freechips.rocketchip.system.ZedboardConfig.behav_srams.v $current_file_group];
::set_property type {verilogSource} $current_file;
::set_property processing_order {normal} $current_file;
set current_file [::ipx::add_file plusarg_reader.v $current_file_group];
::set_property type {verilogSource} $current_file;
::set_property processing_order {normal} $current_file;
set current_file [::ipx::add_file freechips.rocketchip.system.ZedboardConfig.v $current_file_group];
::set_property type {verilogSource} $current_file;
::set_property processing_order {normal} $current_file;
set current_file_group [::ipx::add_file_group xilinx_xpgui $top];
::set_property display_name {UI Layout} $current_file_group;
::set_property env_ids {:vivado.xilinx.com:xgui.ui} $current_file_group;
# Add file objects
set current_file [::ipx::add_file xgui/ExampleRocketSystem_v1_0.tcl $current_file_group];
::set_property type {tclSource} $current_file;
::set_property processing_order {normal} $current_file;
::set_property xgui_version {2} $current_file;
