open_project rocket_board_design/rocket_board_design.xpr
launch_sdk -workspace rocket_board_design/rocket_board_design.sdk -hwspec rocket_board_design/rocket_board_design.sdk/main_design_wrapper.hdf
close_project
